### ISSUE TITLE
Update mod.hjson

### ISSUE THREAD

**Issue by Gugui322** [chinhonnang/mindustry-mod-scrapdusrty#1]
Add your name and github link. Very good mod.

**Comment by chinhonnang** [comment]
> Add your name and github link. Very good mod.

the mod can now be found on the mod browser in the game

**Comment by Gugui322** [comment]
@chinhonnang can i make a suggestion?

**Comment by chinhonnang** [comment]
> @chinhonnang can i make a suggestion?

yes. for entirely new mods
